const {chromium} = require(process.env.RULEATLAS_PLAYWRIGHT || 'playwright');
const assert = require('node:assert/strict');
(async()=>{
 require('node:fs').mkdirSync('test-results',{recursive:true});
 const options={headless:true,args:['--no-sandbox']}; if(process.env.RULEATLAS_CHROMIUM) { options.executablePath=process.env.RULEATLAS_CHROMIUM; options.args=(await import(process.env.RULEATLAS_CHROMIUM_HELPER)).default.args; } const browser=await chromium.launch(options);
 const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 for(let attempt=0;attempt<20;attempt++){try{await page.goto(process.env.RULEATLAS_URL || 'http://127.0.0.1:8765');break;}catch(e){if(attempt===19)throw e;await new Promise(r=>setTimeout(r,250));}}
 await page.locator('.result').first().waitFor();
 await page.selectOption('#source-filter','demo');
 await page.selectOption('#method','attack');
 await page.fill('#query','T1059.001');
 await page.click('#search-form button[type=submit]');
 await page.waitForFunction(()=>document.querySelector('#results-count').textContent==='1 results');
 await page.waitForFunction(()=>document.querySelector('#rule-detail h2')?.textContent.includes('PowerShell'));
 await page.fill('#query','T1059');
 await page.click('#search-form button[type=submit]');
 await page.waitForFunction(()=>document.querySelector('#rule-detail h2')?.textContent.includes('Container'));
 await page.check('#expand');
 await page.waitForFunction(()=>document.querySelector('#results-count').textContent==='2 results');
 await page.uncheck('#expand');
 await page.selectOption('#method','hybrid');
 await page.fill('#query','group');
 await page.click('#search-form button[type=submit]');
 await page.waitForFunction(()=>document.querySelector('#results-count').textContent==='2 results');
 await page.locator('.result').filter({hasText:'External member'}).click();
 await page.waitForFunction(()=>document.querySelector('#rule-detail h2')?.textContent.includes('External member'));
 await page.locator('textarea[aria-label="Scenario requirement phrases"]').fill('ADD_GROUP_MEMBER\nrare ASN');
 await page.getByRole('button',{name:'Find supporting lines'}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.review-line').length===2);
 assert.match(await page.locator('.review-line').nth(1).textContent(),/not established/);
 const downloadPromise=page.waitForEvent('download');await page.click('#export-csv');const download=await downloadPromise;
 assert.equal(download.suggestedFilename(),'ruleatlas-results.csv');await download.saveAs('test-results/results.csv');
 await page.click('[data-tab=sources]');
 assert.equal(await page.locator('#source-list .source-card').count(),25);
 assert.equal(await page.inputValue('#sync-transport'),'archive');
 const syncRequests=[];
 await page.route('**/api/sync',async route=>{syncRequests.push(route.request().postDataJSON());await route.fulfill({status:202,contentType:'application/json',body:'{"status":"started"}'});});
 await page.route('**/api/job',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({status:'failed',messages:[],results:[{source_id:'sigma',status:'failed',error:'Test network unavailable'}]})}));
 await page.locator('#source-list .source-card').first().locator('input[type=checkbox]').check();
 await page.click('#sync-selected');
 await page.waitForFunction(()=>document.querySelector('#job-status').textContent.startsWith('FAILED')&&!document.querySelector('#sync-selected').disabled);
 assert.equal(syncRequests[0].transport,'archive');
 await page.selectOption('#sync-transport','git');
 await page.click('#sync-selected');
 await page.waitForFunction(()=>!document.querySelector('#sync-selected').disabled);
 assert.equal(syncRequests[1].transport,'git');
 await page.selectOption('#sync-transport','archive');
 await page.unroute('**/api/sync');await page.unroute('**/api/job');
 await page.locator('#source-list .source-card').first().getByRole('button').click();
 assert.equal(await page.locator('.assessment').count(),6);
 const note=page.locator('textarea[aria-label="maintenance note"]');const original=await note.inputValue();await note.fill(original+' Browser QA.');
 await page.getByRole('button',{name:'Save local assessment'}).click();await page.waitForFunction(()=>!document.querySelector('#source-dialog').open);
 await page.locator('#source-list .source-card').first().getByRole('button').click();
 assert.equal(await note.inputValue(),original+' Browser QA.');await note.fill(original);await page.getByRole('button',{name:'Save local assessment'}).click();await page.waitForFunction(()=>!document.querySelector('#source-dialog').open);
 await page.click('[data-tab=search]');
 await page.fill('#query','');await page.click('#search-form button[type=submit]');await page.waitForFunction(()=>document.querySelector('#results-count').textContent==='8 results');
 await page.locator('.result').filter({hasText:'External member'}).click();
 await page.waitForFunction(()=>document.querySelector('#rule-detail h2')?.textContent.includes('External member'));
 await page.screenshot({path:'test-results/ui-preview.png',fullPage:true});
 await page.setViewportSize({width:430,height:900});
 await page.screenshot({path:'test-results/mobile.png',fullPage:true});
 const dimensions=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));
 assert.ok(dimensions.scroll<=dimensions.width+1,JSON.stringify(dimensions));
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({passed:['exact sub-technique search','parent expansion toggle','source filter','scenario evidence lines','CSV download','25-source catalog','archive default and transport selection','failed sync display and retry','six evidence fields','assessment save and restore','mobile width','no browser runtime errors'],dimensions},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
